Global:
  model_name: test_multihead_rec
  debug: false
  use_gpu: true
  epoch_num: 10
  log_smooth_window: 5
  print_batch_step: 1
  save_model_dir: ./output/test_rec_training_full
  save_epoch_step: 1
  eval_batch_step: [0, 50]
  cal_metric_during_train: true
  character_dict_path: ./assets/samples/tiny_rec/dict.txt
  max_text_length: &max_text_length 25
  use_space_char: true

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 0
  regularizer:
    name: L2
    factor: 1.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 32
            depth: 1
            hidden_dims: 64
            kernel_size: [1, 3]
            use_guide: False
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 64
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./assets/samples/tiny_rec/
    label_file_list:
      - ./assets/samples/tiny_rec/train.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecAug:
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 2
    drop_last: false
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./assets/samples/tiny_rec/
    label_file_list:
      - ./assets/samples/tiny_rec/test.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - MultiLabelEncode:
          gtc_encode: NRTRLabelEncode
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 2
    num_workers: 0
